import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:url_launcher/url_launcher.dart';

// ignore: avoid_web_libraries_in_flutter
import 'dart:ui_web' as ui_web;
import 'dart:html' as html;
import 'dart:convert';

import '../core_colors.dart';
import '../core_strings.dart';
import '../core_ui_utils.dart';
import '../core_constants.dart';

class WebToAppScreen extends StatefulWidget {
  const WebToAppScreen({super.key});

  @override
  State<WebToAppScreen> createState() => _WebToAppScreenState();
}

class _WebToAppScreenState extends State<WebToAppScreen> {
  final TextEditingController _urlController = TextEditingController();
  late final WebViewController _webViewController;
  bool _showPreview = false;
  bool _isLoading = false;
  String? _currentUrl;
  bool _isWebViewSupported = true;
  final String _viewId = 'web-preview-iframe';

  @override
  void initState() {
    super.initState();
    if (kIsWeb) {
      _registerWebIframe();
    } else {
      _initController();
    }
  }

  void _registerWebIframe() {
    ui_web.platformViewRegistry.registerViewFactory(_viewId, (int viewId) {
      final iframe = html.IFrameElement()
        ..src = _currentUrl ?? ''
        ..style.border = 'none'
        ..style.width = '100%'
        ..style.height = '100%';
      return iframe;
    });
  }

  void _initController() {
    try {
      _webViewController = WebViewController()
        ..setJavaScriptMode(JavaScriptMode.unrestricted)
        ..setNavigationDelegate(
          NavigationDelegate(
            onPageStarted: (String url) {
              if (mounted) setState(() => _isLoading = true);
            },
            onPageFinished: (String url) {
              if (mounted) setState(() => _isLoading = false);
            },
            onWebResourceError: (WebResourceError error) {
              if (mounted) {
                setState(() => _isLoading = false);
              }
            },
          ),
        );
    } catch (e) {
      debugPrint('WebView not supported on this platform: $e');
      setState(() {
        _isWebViewSupported = false;
      });
    }
  }

  void _handleConvert() {
    String url = _urlController.text.trim();
    if (url.isEmpty) {
      ktShowCustomToast(context, KtStrings.invalidUrl);
      return;
    }

    if (!url.startsWith('http://') && !url.startsWith('https://')) {
      url = 'https://$url';
    }

    setState(() {
      _currentUrl = url;
      _showPreview = true;
    });

    if (!kIsWeb && _isWebViewSupported) {
      _webViewController.loadRequest(Uri.parse(url));
    }
  }

  void _showDownloadOptions() {
    ktShowDetailsSheet(
      context: context,
      title: KtStrings.convertToApp,
      icon: Icons.app_shortcut,
      themeColor: ktPrimary,
      details: [
        {
          'label': 'PLATFORM',
          'value': kIsWeb ? 'Web / Android' : 'Android',
          'isHighlight': true,
        },
        {
          'label': 'URL',
          'value': _currentUrl ?? _urlController.text,
        },
        {
          'label': 'STATUS',
          'value': 'Conversion Ready',
          'color': ktSuccess,
        },
      ],
      actions: [
        ElevatedButton.icon(
          onPressed: () {
            Navigator.pop(context);
            _handleApkDownload();
          },
          icon: const Icon(Icons.android, color: Colors.white),
          label: const Text(KtStrings.downloadNativeApk),
          style: ElevatedButton.styleFrom(
            backgroundColor: ktSuccess,
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          ),
        ),
        OutlinedButton.icon(
          onPressed: () {
            Navigator.pop(context);
            _handleWebAppInstall();
          },
          icon: const Icon(Icons.web, color: ktPrimary),
          label: const Text(KtStrings.installWebApp),
          style: OutlinedButton.styleFrom(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            side: const BorderSide(color: ktPrimary),
          ),
        ),
      ],
    );
  }

  void _handleApkDownload() async {
    ktShowCustomToast(context, 'Preparing APK for ${_currentUrl ?? "Website"}...');
    
    if (kIsWeb) {
      // Simulate APK download by creating a blob
      final String mockContent = 'Mock APK Content for ${_currentUrl ?? "App"}\nGenerated by KT Apps';
      final bytes = utf8.encode(mockContent);
      final blob = html.Blob([bytes]);
      final url = html.Url.createObjectUrlFromBlob(blob);
      final anchor = html.document.createElement('a') as html.AnchorElement
        ..href = url
        ..style.display = 'none'
        ..download = 'native_app.apk';
      html.document.body?.children.add(anchor);
      anchor.click();
      html.document.body?.children.remove(anchor);
      html.Url.revokeObjectUrl(url);
      
      ktShowCustomToast(context, 'Native APK download started!');
    } else {
      // On mobile, we could open a download link
      final Uri url = Uri.parse('https://github.com/flutter/flutter/releases'); // Placeholder
      if (await canLaunchUrl(url)) {
        await launchUrl(url);
      }
    }
  }

  void _handleWebAppInstall() async {
    if (_currentUrl == null) {
      ktShowCustomToast(context, KtStrings.invalidUrl);
      return;
    }

    ktShowCustomToast(context, 'Creating Web App Shortcut...');
    
    if (kIsWeb) {
      // Create a more sophisticated HTML launcher that looks like an app
      final String shortcutHtml = '''
<!DOCTYPE html>
<html>
<head>
    <title>KT App Launcher</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; margin: 0; background-color: #0f172a; color: white; text-align: center; }
        .card { background: #1e293b; padding: 2rem; border-radius: 1.5rem; box-shadow: 0 10px 25px rgba(0,0,0,0.5); border: 1px solid rgba(255,255,255,0.1); max-width: 90%; }
        .btn { background: #6366f1; color: white; border: none; padding: 1rem 2rem; border-radius: 0.75rem; font-weight: bold; cursor: pointer; text-decoration: none; margin-top: 1.5rem; display: inline-block; transition: transform 0.2s; }
        .btn:hover { transform: scale(1.05); }
        .loader { border: 4px solid #f3f3f3; border-top: 4px solid #6366f1; border-radius: 50%; width: 30px; height: 30px; animation: spin 2s linear infinite; margin: 20px auto; }
        @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
    </style>
    <script>
        setTimeout(function() {
            window.location.href = "${_currentUrl}";
        }, 1500);
    </script>
</head>
<body>
    <div class="card">
        <h2 style="margin: 0">Launching your App</h2>
        <p style="color: #94a3b8">${_currentUrl}</p>
        <div class="loader"></div>
        <p>Redirecting you now...</p>
        <a href="${_currentUrl}" class="btn">Open Manually</a>
    </div>
</body>
</html>
''';
      final bytes = utf8.encode(shortcutHtml);
      final blob = html.Blob([bytes], 'text/html');
      final url = html.Url.createObjectUrlFromBlob(blob);
      final anchor = html.document.createElement('a') as html.AnchorElement
        ..href = url
        ..style.display = 'none'
        ..download = 'KT_App_Shortcut.html';
      html.document.body?.children.add(anchor);
      anchor.click();
      html.document.body?.children.remove(anchor);
      html.Url.revokeObjectUrl(url);

      ktShowCustomToast(context, 'Web Shortcut created successfully!');
    } else {
      await launchUrl(Uri.parse(_currentUrl!), mode: LaunchMode.externalApplication);
    }
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      backgroundColor: isDark ? ktBgDark : ktLightScaffoldBg,
      appBar: AppBar(
        title: const Text(
          KtStrings.convertToApp,
          style: TextStyle(fontWeight: FontWeight.w900, color: Colors.white),
        ),
        backgroundColor: Colors.transparent,
        elevation: 0,
        flexibleSpace: Container(
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              colors: [ktPrimary, ktSecondary],
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
            ),
          ),
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new, color: Colors.white, size: 20),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: Column(
        children: [
          _buildInputSection(isDark),
          Expanded(
            child: _showPreview ? _buildPreviewSection(isDark) : _buildEmptyState(isDark),
          ),
        ],
      ),
    );
  }

  Widget _buildInputSection(bool isDark) {
    return Container(
      padding: const EdgeInsets.all(20),
      margin: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: isDark ? ktCardBg : Colors.white,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: isDark ? ktBorderWhite10 : Colors.black.withOpacity(0.05)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 20,
            offset: const Offset(0, 8),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            KtStrings.enterUrl,
            style: TextStyle(
              color: isDark ? Colors.white70 : ktDarkText,
              fontSize: 12,
              fontWeight: FontWeight.w800,
              letterSpacing: 1,
            ),
          ),
          const SizedBox(height: 12),
          TextField(
            controller: _urlController,
            style: TextStyle(color: isDark ? Colors.white : ktDarkText, fontWeight: FontWeight.w600),
            decoration: InputDecoration(
              hintText: KtStrings.urlHint,
              hintStyle: TextStyle(color: isDark ? Colors.white24 : Colors.black26),
              prefixIcon: const Icon(Icons.link, color: ktPrimary),
              filled: true,
              fillColor: isDark ? Colors.black26 : ktGray50,
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(16),
                borderSide: BorderSide.none,
              ),
              contentPadding: const EdgeInsets.symmetric(vertical: 16),
            ),
            keyboardType: TextInputType.url,
            textInputAction: TextInputAction.go,
            onSubmitted: (_) => _handleConvert(),
          ),
          const SizedBox(height: 20),
          SizedBox(
            width: double.infinity,
            height: 56,
            child: ElevatedButton(
              onPressed: _handleConvert,
              style: ElevatedButton.styleFrom(
                backgroundColor: ktPrimary,
                foregroundColor: Colors.white,
                elevation: 4,
                shadowColor: ktPrimary.withOpacity(0.4),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
              ),
              child: const Text(
                KtStrings.convertToApp,
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.w900, letterSpacing: 0.5),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPreviewSection(bool isDark) {
    return Container(
      margin: const EdgeInsets.fromLTRB(16, 0, 16, 16),
      decoration: BoxDecoration(
        color: isDark ? ktCardBg : Colors.white,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: isDark ? ktBorderWhite10 : Colors.black.withOpacity(0.05)),
      ),
      clipBehavior: Clip.antiAlias,
      child: Stack(
        children: [
          Column(
            children: [
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
                color: isDark ? Colors.white.withOpacity(0.05) : ktGray50,
                child: Row(
                  children: [
                    const Icon(Icons.remove_red_eye_outlined, size: 18, color: ktPrimary),
                    const SizedBox(width: 12),
                    const Text(
                      KtStrings.webPreview,
                      style: TextStyle(fontWeight: FontWeight.w800, fontSize: 13),
                    ),
                    const Spacer(),
                    IconButton(
                      icon: const Icon(Icons.open_in_new, size: 18, color: ktPrimary),
                      onPressed: () async {
                        if (_currentUrl != null) {
                          await launchUrl(Uri.parse(_currentUrl!), mode: LaunchMode.externalApplication);
                        }
                      },
                      tooltip: 'Open in new tab',
                      constraints: const BoxConstraints(),
                      padding: EdgeInsets.zero,
                    ),
                    if (_isLoading) ...[
                      const SizedBox(width: 12),
                      const SizedBox(
                        width: 16,
                        height: 16,
                        child: CircularProgressIndicator(strokeWidth: 2, color: ktPrimary),
                      ),
                    ],
                  ],
                ),
              ),
              Expanded(
                child: Stack(
                  children: [
                    kIsWeb
                        ? HtmlElementView(
                            key: ValueKey(_currentUrl),
                            viewType: _viewId,
                          )
                        : (_isWebViewSupported
                            ? WebViewWidget(controller: _webViewController)
                            : _buildWebViewFallback(isDark)),
                    if (kIsWeb)
                      Positioned(
                        bottom: 20,
                        left: 0,
                        right: 0,
                        child: Center(
                          child: Container(
                            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                            decoration: BoxDecoration(
                              color: Colors.black.withOpacity(0.7),
                              borderRadius: BorderRadius.circular(20),
                            ),
                            child: const Text(
                              'Tip: Some sites block embedded previews for security.',
                              style: TextStyle(color: Colors.white, fontSize: 10),
                            ),
                          ),
                        ),
                      ),
                  ],
                ),
              ),
              Container(
                padding: const EdgeInsets.all(16),
                child: ktEditButton(
                  onPressed: _showDownloadOptions,
                  label: 'Proceed to Conversion',
                ),
              ),
            ],
          ),
          if (_isLoading)
            const Center(
              child: CircularProgressIndicator(color: ktPrimary),
            ),
        ],
      ),
    );
  }

  Widget _buildWebViewFallback(bool isDark) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.open_in_new, size: 48, color: ktPrimary.withOpacity(0.5)),
            const SizedBox(height: 16),
            Text(
              'In-app preview failed to load.',
              textAlign: TextAlign.center,
              style: TextStyle(fontWeight: FontWeight.w600, color: isDark ? Colors.white70 : Colors.black87),
            ),
            const SizedBox(height: 12),
            TextButton(
              onPressed: () async {
                if (_currentUrl != null) {
                  await launchUrl(Uri.parse(_currentUrl!));
                }
              },
              child: const Text('Open in External Browser'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildEmptyState(bool isDark) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Container(
            padding: const EdgeInsets.all(32),
            decoration: BoxDecoration(
              color: ktPrimary.withOpacity(0.1),
              shape: BoxShape.circle,
            ),
            child: Icon(Icons.web_asset, size: 64, color: ktPrimary.withOpacity(0.5)),
          ),
          const SizedBox(height: 24),
          Text(
            'Enter a URL to see preview',
            style: TextStyle(
              color: isDark ? Colors.white54 : Colors.black45,
              fontSize: 16,
              fontWeight: FontWeight.w600,
            ),
          ),
        ],
      ),
    );
  }
}
